import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Front-End Developer | Juan Antonio Vivaldy Saragih</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <div className='h-screen flexCenter'>
            <h1 className='text-4xl font-bold font-sfmono'>LANDING PAGE</h1>
          </div>
      </main>
    </>
  )
}
